server:
  port: 9876

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shangvven/spring-cloud-config/
          username:
          password:
          search-paths: resources
      label: master

evn: dev

--
# test
spring:
  profiles: test

evn: test

--
# prep
spring:
  profiles: prep

evn: prep